### ISSUE TITLE
notebook 5.0.0 unsupported?

### ISSUE THREAD

**Issue by NicolaiRiis** [jupyter/jupyter-drive#142]
Hi,

Jupyter notebook 5.0.0 was released a few days ago. I can't seem to get jupyterdrive to work with this update.

The gdrive folder shows and and shows the files from my drive, however when i choose a folder i get a 500 internal server error.

The terminal that launched the notebook shows the following:

```
[E 15:44:51.429 NotebookApp] Uncaught exception GET /files/gdrive/Loftrum.docx (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/files/gdrive/Loftrum.docx', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Referer': 'http://localhost:8888/view/gdrive/Loftrum.docx', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Accept-Language': 'da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4', 'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Cookie': '[IRemoved TheCookie]})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 2829, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/notebook/files/handlers.py", line 58, in get
        if model['format'] == 'base64':
    KeyError: 'format'
[E 15:44:51.431 NotebookApp] {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Referer": "http://localhost:8888/view/gdrive/Loftrum.docx",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "da-DK,da;q=0.8,en-US;q=0.6,en;q=0.4",
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "Cookie": "[I_Removed_the_cookie]"
    }
[E 15:44:51.432 NotebookApp] 500 GET /files/gdrive/Loftrum.docx (127.0.0.1) 2.61ms referer=http://localhost:8888/view/gdrive/Loftrum.docx

```

**Comment by ian-r-rose** [comment]
Hi @NicolaiRiis. I'm not sure whether `jupyter-drive` should work with Notebook 5.0 (@Carreau would have a better idea), but efforts on Google Drive integration have shifted to a plugin for the upcoming JupyterLab (https://github.com/ian-r-rose/jupyterlab_google_drive).
