### ISSUE TITLE
Can't install with without access to /usr/local/share

### ISSUE THREAD

**Issue by KesterTong** [jupyter/jupyter-drive#76]
This seems to be a problem with ```install_nbextension``` not our code.  Is it possible that nb extensions aren't as compatible with  ```virt_env``` as they should be?  Or is it just that IPython don't want notebook extensions to be part of the virtual env?

**Comment by Carreau** [comment]
Ping @takluyver IIRC. Virtualenv is python specific, so we have no knowlege of it. There is a userflag for that if you want to explicitely install elsewhere.

**Comment by takluyver** [comment]
We've gone back and forth on where to install things by default - for now, the default is systemwide, and you can pass `user=True` if you want to do a per-user installation. We don't want to encode knowledge of a particular Python-specific environment tool into these functions (nbextensions and kernelspecs are not part of the Python environment), but we will look for them in e.g. `share/jupyter/nbextensions` relative to `sys.prefix`, so if you know you're in an environment, you can install there.

**Comment by KesterTong** [comment]
Thanks for the clarification @takluyver.  @Carreau, can you add one more option that allow us to specify an alternate install directory, so that user's can manually specify the path ```sharee/jupyter/nbextensions``` relative to ```sys.prefix```

**Comment by takluyver** [comment]
There's already a `prefix` option. But once you know where you want to install to, the installation process is really just copying files.

**Comment by takluyver** [comment]
(i.e. there's no reason to go through an IPython API if you know where you're installing to - just use standard shutil functions to copy a file or folder)

**Comment by KesterTong** [comment]
Thanks @takluyver, since we already call the IPython API, we have just added the ```prefix``` option.

Closed by #77

**Comment by anddam** [comment]
I stumbled on

    OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

error as well, from @takluyver 's comment I'd think that the *--user* option in [init][1] would do the trick and install files in *~/.ipython* but it's not working, here's the output with and without the --user flag
```
	(colaboratory)me@bibook ~/D/Python> python -m jupyterdrive drive
	Traceback (most recent call last):
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
	    "__main__", fname, loader, pkg_name)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
	    exec code in run_globals
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__main__.py", line 2, in <module>
	    jupyterdrive.main()
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__init__.py", line 96, in main
	    verbose=args.verbose
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__init__.py", line 31, in install
	    nbextensions_dir=path)
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/IPython/html/nbextensions.py", line 176, in install_nbextension
	    ensure_dir_exists(nbext)
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/IPython/utils/path.py", line 588, in ensure_dir_exists
	    os.makedirs(path, mode=mode)
	  File "/Users/me/Development/Python/environments/colaboratory/bin/../lib/python2.7/os.py", line 150, in makedirs
	    makedirs(head, mode)
	  File "/Users/me/Development/Python/environments/colaboratory/bin/../lib/python2.7/os.py", line 157, in makedirs
	    mkdir(name, mode)
	OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
	(colaboratory)me@bibook ~/D/Python> python -m jupyterdrive --user drive
	Traceback (most recent call last):
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
	    "__main__", fname, loader, pkg_name)
	  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
	    exec code in run_globals
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__main__.py", line 2, in <module>
	    jupyterdrive.main()
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__init__.py", line 96, in main
	    verbose=args.verbose
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/jupyterdrive/__init__.py", line 31, in install
	    nbextensions_dir=path)
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/IPython/html/nbextensions.py", line 176, in install_nbextension
	    ensure_dir_exists(nbext)
	  File "/Users/me/Development/Python/environments/colaboratory/lib/python2.7/site-packages/IPython/utils/path.py", line 588, in ensure_dir_exists
	    os.makedirs(path, mode=mode)
	  File "/Users/me/Development/Python/environments/colaboratory/bin/../lib/python2.7/os.py", line 150, in makedirs
	    makedirs(head, mode)
	  File "/Users/me/Development/Python/environments/colaboratory/bin/../lib/python2.7/os.py", line 157, in makedirs
	    mkdir(name, mode)
	OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```

In both cases I get a permision denied error for '/usr/local/share/jupyter'.

Did I misunderstood the *"pass user=True* part that @takluyver suggested?
What's the proper way for an user to install into his home directory?


[1]: https://github.com/jupyter/jupyter-drive/blob/master/jupyterdrive/__init__.py#L68

**Comment by takluyver** [comment]
@KesterTong @Carreau - there's a `--user` option, but it looks like you don't actually use it when calling `install()`.

**Comment by KesterTong** [comment]
I can't remember if I ever used --user.  I may have used --path all along.  Or maybe I just started installing using sudo.  Sorry for the confusion @anddam, it looks like your final command line is close to what I was using at one point.  @takluyver I will investigate the ```--user``` option, maybe it once did something and stopped working

**Comment by takluyver** [comment]
I think all the machinery for it is there, you're just missing a `user=args.user` here: https://github.com/jupyter/jupyter-drive/blob/master/jupyterdrive/__init__.py#L97

**Comment by KesterTong** [comment]
@takluyver you are right.  I created #99 so we remember to fix this.
