### ISSUE TITLE
TypeError: install_nbextension() got an unexpected keyword argument 'user'

### ISSUE THREAD

**Issue by nwparker** [jupyter/jupyter-drive#81]
After creating a user profile with
```
ipython profile create colab
```

And running 
```
python -m jupyterdrive colab
```

I am met with:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/neil/Projects/jupyter-drive/jupyterdrive/__main__.py", line 2, in <module>
    jupyterdrive.main()
  File "jupyterdrive/__init__.py", line 96, in main
    verbose=args.verbose
  File "jupyterdrive/__init__.py", line 31, in install
    nbextensions_dir=path)
TypeError: install_nbextension() got an unexpected keyword argument 'user'
```

**Comment by Carreau** [comment]
Which version of IPython are you running ? Jupyterdrive is compatible only with 3.0. 

`python -c 'import IPython; print(IPython.sys_info())'` to get version.

**Comment by nwparker** [comment]
I was running 2.x
Thanks for poining out the issue!
